### ISSUE TITLE
beim installieren Error SQLSTATE[HY093]: 

### ISSUE THREAD

**Issue by winnitue** [dneustadt/DneCustomJsCss#2]
Hallo, ich bekomme beim installieren immer die Meldung Error
SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
Ich habe das schon zig mal gelöscht, heruntergeladen und versucht neu zu installieren. Leider erfolglos.
Shopware Version 5.7.6
Danke

**Comment by dneustadt** [comment]
Neues Release mit einem Fix dafür ist raus.

**Comment by winnitue** [comment]
Thank You !!!
