### ISSUE TITLE
Suchfunktion innerhalb des Containers aktivieren

### ISSUE THREAD

**Issue by ghost** [dneustadt/DneCustomJsCss#3]
Hi erstmal vielen Dank für dieses großartige Plugin, leider funktioniert die Suche (strg + F) mit dem Container nicht. Es werden zwar die Ergebnisse markiert, jedoch springt er bei längerem Inhalt nicht zur gewünschten Stelle kann man das anpassen? Vielleicht ist es ja auch mein Fehler? 

Lg Mark

**Comment by ghost** [comment]
Was auch interessant wäre die JS / CSS Injektionen pro Seite / Kategorie / Artikel steuerbar zu machen ist das möglich? :)

**Comment by dneustadt** [comment]
Hi, danke auch für das Lob ;) Der Ace Code Editor hat eigentlich eine eigene Search Box, die auch gut funktioniert. In der Vue Component von Shopware, die ich auch verwende, ist die allerdings wohl deaktiviert. Ich denke da kann man schon was dran machen, dass man die wieder aktiviert bekommt. Ich kann allerdings leider nicht versprechen, wann ich dazu komme. Spätestens zum nächsten größeren Shopware Release.

Was das CSS/JS nur auf einzelnen Seiten angeht. Dafür könnte man ja prinzipiell die Klassen des `body` Tags heranziehen. In Kategorien wäre z.B. `is-ctl-navigation`, auf Produktdetailseiten `is-ctl-product` usw.

```css
.is-ctl-product {
    p {
        /* styles nur auf produktdetailseiten */
    }
}
```

```javascript
if (document.body.classList.contains('is-ctl-product')) {
    // nur ausgeführt auf produktdetailseiten
    alert('hello world');
}
```

**Comment by ghost** [comment]
Vielen Vielen Dank für die Antwort! Hat mir jetzt bereits geholfen 😊

 

Ich feiere alles was von FROSH kommt. Besonders das Plugin custom css / java!! Weiter so!
